# Generated by Django 4.2.7 on 2023-12-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图管理'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '反馈', 'verbose_name_plural': '反馈管理'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户管理'},
        ),
    ]
