# Generated by Django 4.2.7 on 2023-12-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_banner_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Feedback',
        ),
    ]
