# Generated by Django 4.2.7 on 2024-12-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_message_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/', verbose_name='头像'),
        ),
    ]
